# -*- coding: utf-8 -*-
"""datos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LBAHSPVQ9Yf_Ewbok2CxUGG1aMaSq0Zs
"""

import pandas as pd
data = pd.read_csv('calles_de_medellin_con_acoso.csv', sep = ";").values
print(data)